apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-frontend
    spec:
      containers:
        - name: {{ .Values.appName }}-frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            limits:
              memory: "{{ .Values.frontend.memory }}"
              cpu: "{{ .Values.frontend.cpu }}"
        - name: process-exporter
          image: ncabatoff/process-exporter:latest
          args:
            - '--config.path=/config/process.yml'
          ports:
            - containerPort: 9256
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}-frontend
spec:
  selector:
    app: {{ .Values.appName }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP