apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appName}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
  namespace: {{ .Values.appName}}
  labels:
    run: {{ .Values.appName}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: {{ .Values.appName}}
  template:
    metadata:
      labels:
        run: {{ .Values.appName}}
    spec:
      containers:
        - name: {{ .Values.appName}}-container
          image: kodekloud/irongallery:2.0
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/data
            
            - name: images
              mountPath: /usr/share/nginx/html/uploads
      volumes:
        - name: config
          emptyDir: {}

        - name: images
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}-db
  namespace: {{ .Values.appName}}
  labels:
    db: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
        - name: {{ .Values.appName}}-db-container
          image: kodekloud/irondb:2.0
          env:
            - name: MYSQL_DATABASE
              value: database_web

            - name: MYSQL_USER
              value: user_web

            - name: MYSQL_ROOT_PASSWORD
              value: i6I8GOw0vrSd

            - name: MYSQL_PASSWORD
              value: 9I2Jr6plV1rs

          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
      volumes:
        - name: db
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-db-service
  namespace: {{ .Values.appName}}
spec:
  selector:
    db: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iron-gallery-ingress
  namespace: {{ .Values.appName}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.appName }}
spec:
  selector:
    run: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
